# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EqZ6XP6RLBgl18CL5uSYbJj7JFEtDE4D
"""

def load_stock_prices():

    return {
        "AAPL": 190.50,
        "GOOGL": 2700.75,
        "TSLA": 800.10,
        "AMZN": 3400.30,
        "INFY": 1500.00
    }

def save_investment_to_file(data, filename="investment_report.txt"):
    with open(filename, "w") as f:
        f.write("Stock Investment Summary\n")
        f.write("--------------------------\n")
        for stock, (qty, total) in data.items():
            f.write(f"{stock}: {qty} shares = ₹{total:.2f}\n")
        f.write("--------------------------\n")
        grand_total = sum(total for qty, total in data.values())
        f.write(f"Total Investment: ₹{grand_total:.2f}\n")

def main():
    stock_prices = load_stock_prices()
    investment_data = {}

    print("Available Stocks and Prices (INR):")
    for stock, price in stock_prices.items():
        print(f"{stock}: ₹{price}")

    print("\nEnter quantity of stocks you own:")

    for stock in stock_prices:
        try:
            qty = int(input(f"How many shares of {stock} do you own? "))
            total_value = qty * stock_prices[stock]
            investment_data[stock] = (qty, total_value)
        except ValueError:
            print("Invalid input. Skipping this stock.")
            investment_data[stock] = (0, 0.0)

    print("\nYour Investment Summary:")
    total_investment = 0
    for stock, (qty, total) in investment_data.items():
        print(f"{stock}: {qty} shares = ₹{total:.2f}")
        total_investment += total

    print(f"\nTotal Investment: ₹{total_investment:.2f}")

    save_investment_to_file(investment_data)
    print("\nInvestment report saved to 'investment_report.txt'.")

if __name__ == "__main__":
    main()
